services:
  - type: web
    name: hpp-canada-inventory
    runtime: docker
    plan: free
    envVars:
      - key: API_KEY
        value: changeme
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: RENDER_EXTERNAL_URL
        fromService:
          name: hpp-canada-inventory
          type: web
          property: host
